### ISSUE TITLE
Deploy to maven central

### ISSUE THREAD

**Issue by stefan-niedermann** [commonsguy/cwac-anddown#14]
Please deploy to maven central or jcenter.

**Comment by commonsguy** [comment]
@stefan-niedermann This library is already available as an artifact from a Maven-style repository. Instructions are in [the project `README`](https://github.com/commonsguy/cwac-anddown).

One of my bedrock principles is that unnecessarily centralization is intrinsically bad, which is why I eschew the "everything-but-the-kitchen-sink" repositories. You are welcome to attempt to convince me why it is in my interest to go counter to this principle.

**Comment by pizzamaker** [comment]
@commonsguy This is a requirement to have the app on F-Droid: https://f-droid.org/forums/topic/owncloud-notes/

**Comment by commonsguy** [comment]
@pizzamaker The point behind F-Droid, I thought, was to help break the dependency upon a proprietary silo (Google Play Store). I fail to see how F-Droid forcing dependencies upon proprietary silos (Maven Central/JCenter) makes ethical sense.

With respect to my open source libraries, developers that cannot use the AARs from my repo are certainly welcome to use the source code that I am publishing, directly or as inspiration for their own work.

**Comment by mendhak** [comment]
Future searchers: this works on jitpack.  Releases don't seem to build, but you can pick a commit, like

    compile 'com.github.commonsguy:cwac-anddown:dedb48ec0f'
