### ISSUE TITLE
Apostrophe converted to &#39;

### ISSUE THREAD

**Issue by duskox** [commonsguy/cwac-anddown#17]
Hello, not sure if I am doing something wrong but I am being sent a string that I need to convert to a list, it has \n characters dividing the list items, and that works fine. The problem I have is with ' character. In string it is passed as \' and is converted to `&#39;` in text.

**Comment by commonsguy** [comment]
I'm not really doing anything with the text, other than passing the Markdown source to hoedown, then passing the HTML back.

By "is converted to `&#39;`", do you literally mean that you are seeing five characters (`&`, `#`, `3`, `9`, and `;`)?

**Comment by duskox** [comment]
Yes, I see those characters in the output string and that ofcourse is shown to the user. Text is french so that is why I use apostrophes.

**Comment by duskox** [comment]
Ok, I think AndDown is doing it correct, it is an HTML code for apostrophe, but since I am not displaying it in webview I get the code itself shown. Maybe I should use Bypass as it is suggested on AndDown pages?

**Comment by commonsguy** [comment]
Well, you are getting HTML back from hoedown and AndDown. If you are using `Html.fromHtml()` to display that to the user (instead of the `WebView`), usually it handles HTML entities, though perhaps it is failing on this one for some reason. Whether Bypass will be an improvement here or not, I cannot say.

Also note that apostrophes do not need to be escaped in Markdown.

I'm going to mark this as closed, since it would not appear that AndDown is the source of your problem. If you find evidence to the contrary, let me know and I can reopen it.

If you have further concerns on this topic, but they are not signs of a bug in AndDown, you might wish to use Stack Overflow, per [the project documentation](https://github.com/commonsguy/cwac-anddown#questions).

**Comment by duskox** [comment]
Yes, please close it, AndDown is not faulty, but I had no idea where to look. Thanks.
