### ISSUE TITLE
Release build[R8 enabled] in Android Studio 3.5.1 crashes: UnsatisfiableLinkError

### ISSUE THREAD

**Issue by abhishekBansal** [commonsguy/cwac-anddown#23]
Crashstack

> java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String c.c.a.a.a.a(java.lang.String, int, int) (tried Java_c_c_a_a_a_a and Java_c_c_a_a_a_a__Ljava_lang_String_2II)
>         at c.c.a.a.a.a(Native Method)
>         at <package>.DetailActivity.onCreate(:1)
>         at android.app.Activity.performCreate(Activity.java:7802)
>         at android.app.Activity.performCreate(Activity.java:7791)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by commonsguy** [comment]
You did not follow [the instructions for filing bug reports](https://github.com/commonsguy/cwac-anddown/blob/master/CONTRIBUTING.md#contributing-bug-reports).

You might try adding a `-keep` directive for `com.commonsware.cwac.anddown.AndDown` to your ProGuard/R8 configuration.

Otherwise, if you follow [the instructions for filing bug reports](https://github.com/commonsguy/cwac-anddown/blob/master/CONTRIBUTING.md#contributing-bug-reports) and give me a way to reproduce your problem, I will be happy to look at it.

Or, consider using a different library, such as:

- [commonmark-java](https://github.com/atlassian/commonmark-java)
- [Markwon](https://github.com/noties/Markwon)
